eating/blueprints/fountains/routes.py
from flask import Blueprint, render_template, redirect, flash, url_for
from flask_login import current_user
from eating.forms import RateFountain, AddFountain
import eating.crud as crud


"""Fountains Blueprint"""

fountains_bp = Blueprint("fountains_bp", "__name__")


""" Fountain Routes """


@fountains_bp.route("/fountain_place/<fountain_id>", methods=["GET", "POST"])
def fountain_place(fountain_id):
    """Renders page for specific fountain, POST creates a new rating for the fountain"""

    form = RateFountain()
    fountain = crud.get_fountain_by_id(fountain_id)

    if current_user.is_authenticated:
        user_id = current_user.id
        rated = crud.get_user_rating_for_fountain(
            user_id=user_id, fountain_id=fountain_id
        )

        if form.validate_on_submit():
            star_rating = form.star_rating.data
            review = form.review.data

            if rated:
                pass

            new_rating = crud.create_fountain_rating(
                user_id=user_id,
                fountain_id=fountain_id,
                star_rating=star_rating,
                review=review,
            )

            flash("Your review has been accepted, thank you!", category="success")
            return redirect(url_for("fountain_place", fountain_id=fountain_id))

        return render_template(
            "fountain_place.html", form=form, fountain=fountain, rated=rated
        )

    return render_template(
        "fountain_place.html", form=form, fountain=fountain, rated=rated
    )


@fountains_bp.route("/add_fountain", methods=["GET", "POST"])
def add_fountain():
    """Return page to add a new fountain, accepts and processes new fountain submission"""

    form = AddFountain()

    if form.validate_on_submit():
        if crud.get_fountain_by_name(name=form.name.data):
            flash("Fountain name already exists", category="danger")
            return redirect(url_for("add_fountain"))

        new_fountain = crud.create_fountain(
            name=form.name.data,
            image_url=form.image_url.data,
            land=form.land.data,
            description=form.description.data,
            x_coord=form.x_coord.data,
            y_coord=form.y_coord.data,
        )
        flash("Fountain added successfully", category="success")

        return redirect(url_for("add_fountain"))

    return render_template("add_fountain.html", form=form)

eating/blueprints/main/routes.py
from flask import Blueprint, render_template
import eating.crud as crud

main = Blueprint("main", "__name__")


@main.route("/")
def home():
    """Homepage"""

    restaurants = crud.get_3_restaurants()

    return render_template(
        "home.html",
        restaurants=restaurants,
        total_ratings=crud.total_ratings,
        star_avg=crud.star_avg,
        generate_stars=crud.generate_stars,
    )

eating/blueprints/restaurants/routes.py
from flask import Blueprint, render_template, redirect, flash, url_for
import eating.crud as crud
from eating.forms import AddRestaurant, RateRestaurant
from flask_login import current_user

"""Restaurant Blueprint"""

restaurants_bp = Blueprint("restaurants_bp", "__name__")


""" Restaurant Routes """


@restaurants_bp.route("/restaurants")
def restaurants():
    """Renders page with all restaurants from db"""

    restaurants = crud.get_all_restaurants()

    return render_template(
        "restaurants.html",
        restaurants=restaurants,
        total_ratings=crud.total_ratings,
        star_avg=crud.star_avg,
        generate_stars=crud.generate_stars,
    )


@restaurants_bp.route("/add_restaurant", methods=["GET", "POST"])
def add_restaurant():
    """Return page to add a new restaurant, accepts and processes new restaurant submission"""

    form = AddRestaurant()

    if form.validate_on_submit():
        if crud.get_restaurant_by_name(name=form.name.data):
            # if Restaurant.query.filter_by(name=form.name.data).first():
            flash("Restaurant already exists", category="danger")
            return redirect(url_for("restaurants_bp.add_restaurant"))

        # cuisines = []
        # for cuisine in form.cuisines.data:
        #     cuisines.append(get_cuisine_by_name(cuisine))

        # print(cuisines)

        crud.create_restaurant(
            name=form.name.data,
            image_url=form.image_url.data,
            land=form.land.data,
            expense=form.expense.data,
            full_service=form.full_service.data,
            x_coord=form.x_coord.data,
            y_coord=form.y_coord.data,
        )

        flash("Restaurant added successfully", category="success")

        return redirect(url_for("restaurants_bp.add_restaurant"))

    return render_template("addrestaurant.html", form=form)


@restaurants_bp.route("/eating_place/<rest_id>", methods=["GET", "POST"])
def eating_place(rest_id):
    """Renders page for specific restaurant, POST creates a new rating for the restaurant"""

    form = RateRestaurant()
    restaurant = crud.get_restaurant_by_id(rest_id)
    rest_len = crud.restaurants_count()

    if current_user.is_authenticated:
        user_id = current_user.id
        rated = crud.get_user_restaurant_rating(user_id=user_id, rest_id=rest_id)

        if form.validate_on_submit():
            star_rating = form.star_rating.data
            review = form.review.data

            # if Rating.query.filter_by(user_id=user_id, rest_id=rest_id).first():
            #     pass # what was I doing here?

            crud.create_rating(
                user_id=user_id, rest_id=rest_id, star_rating=star_rating, review=review
            )

            flash("Your review has been accepted, thank you!", category="success")

            return redirect(url_for("restaurants_bp.eating_place", rest_id=rest_id))

        return render_template(
            "eating_place.html",
            restaurant=restaurant,
            form=form,
            rated=rated,
            rest_len=rest_len,
            total_ratings=crud.total_ratings,
            star_avg=crud.star_avg,
            restaurant_reviews=crud.restaurant_reviews,
            get_user_by_id=crud.get_user_by_id,
            get_restaurant_by_id=crud.get_restaurant_by_id,
            generate_stars=crud.generate_stars,
            get_star_rating=crud.get_star_rating,
        )

    return render_template(
        "eating_place.html",
        restaurant=restaurant,
        form=form,
        rest_len=rest_len,
        total_ratings=crud.total_ratings,
        star_avg=crud.star_avg,
        restaurant_reviews=crud.restaurant_reviews,
        get_user_by_id=crud.get_user_by_id,
        get_restaurant_by_id=crud.get_restaurant_by_id,
        generate_stars=crud.generate_stars,
        get_star_rating=crud.get_star_rating,
    )


@restaurants_bp.route("/update_restaurant/<rest_id>", methods=["POST"])
def update_restaurant(rest_id):
    """Updates information about a restaurant"""

    pass

eating/templates/add_fountain.html
{% extends 'base.html' %} 

{% include 'navbar.html' %}

{% block title %}Add Fountain
{% endblock %}

{% block content %} 

<div class="container justify-content-md-center">
    <form class="row" method="post" action="{{ url_for('fountains_bp.add_fountain') }}">
        <div class="col">
            <h2 class="heading">Add a Fountain</h2>
                {{ form.csrf_token }}
            <div class="form-group col-4">
                {{ form.name.label }}
                {{ form.name(class="form-control") }}
            </div>
            <div class="form-group col-4">
                {{ form.image_url.label }}
                {{ form.image_url(class="form-control") }}
            </div>
            <div class="form-group col-4">
                {{ form.land.label }}
                {{ form.land }}
            </div>
            <div class="form-group col-4">
                {{ form.description.label }}
                {{ form.description(class="form-control") }}
            </div>
            <div class="form-group col-4">
                {{ form.x_coord.label }}
                {{ form.x_coord(class="form-control") }}
            </div>
            <div class="form-group col-4">
                {{ form.y_coord.label }}
                {{ form.y_coord(class="form-control") }}
            </div>
            <div class="form-group col">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </div>
    </form>
</div>



{% endblock %}

eating/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      property="og:title"
      content="Eating Disneyland! The Guide to Eating Around the Parks"
    />
    <meta
      property="og:image"
      content="https://www.eatingdisneyland.com/hp_image_preview"
    />
    <meta name="author" content="Sean Fagan" />
    <meta name="description" content="A guide to the restaurants, snacks, and drinks around Disneyland Park and Disney California Adventure" />

    {%- block styles %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600&family=Eczar:wght@400;600;700&family=Mouse+Memoirs&family=Noto+Sans:ital,wght@0,400;0,600;0,800;1,400&family=Philosopher&family=Roboto:ital,wght@0,300;0,400;0,500;1,300&display=swap"
      rel="stylesheet"
    />
    <script
      src="https://kit.fontawesome.com/55ae4f7d8d.js"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/styles.css') }}"
    />
    {%- endblock styles %}

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block body -%} {% block content -%} {% block map %}{% endblock %} 
    {%-
    endblock content %} 
    {% block scripts %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
    {%- endblock scripts %} 
    {%- endblock body %}
  </body>
  {% block footer %}{% include 'footer.html' %}{% endblock %}
</html>

eating/templates/delete_user.html
{% extends 'base.html' %}

{% include 'navbar.html' %}

{% block title %}Delete Account{% endblock %}

{% block content %} 

<div class="container justify-content-md-center my-4">
    <form class="mx-3" method="post" action="{{ url_for('users_bp.delete_user') }}">
        <h2 class="heading">Delete Your Account</h2>
            {{ form.csrf_token }}
        <div class="form-group m-2 col-4">
            {{ form.type_delete.label }}
            {{ form.type_delete(class="form-control") }}
            {% for field, errors in form.errors.items() %}
            {% if field == 'csrf_token' %} 
            <span></span>
            {% elif field == 'type_delete' %}
            <small class="form-text text-danger ">
                {{ ', '.join(errors) }}
            </small>
            {% endif %}
            {% endfor %}
        
        </div>
        <div class="form-group m-2 col">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
    <!-- <div class="m-2">
        <p style="padding-top:3%">Need to Register an account first?</p>
        <a class="btn btn-primary btn-sm" href="{{ url_for('auth_bp.register') }}" role="button">Register</a>
    </div> -->
</div>

{% endblock %}

eating/templates/eating_place.html
{% extends 'base.html' %}

{% include 'navbar.html' %}

{% block title %}Everybody's Got an Eatin' Place{% endblock %}

{% block content %} 
<div class="container-fluid row mx-0">

    <div class="card text-center mb-3 col" style="height: 100%;">
        <img src="{{ restaurant.image_url }}" class="card-img-top" style="height: 25vw;" alt="There ought to be something here...">
        <div class="card-body">
            <h4 class="card-title" style="text-shadow: #cc9a07 0 1px 1px;">{{ restaurant.name }}</h4>
            <p class="card-text" style="font-style: italic;">{{ restaurant.land }}</p>
            <label class="text-warning" style="text-shadow: #172c65 0 1px 1px;">
                {{ star_avg(restaurant.rest_id, total_ratings(restaurant.rest_id)) }} {{ generate_stars(star_avg(restaurant.rest_id, total_ratings(restaurant.rest_id))) }} 
                <span style="font-style:italic; font-size: smaller;">({{ total_ratings(restaurant.rest_id) }} reviews)</span>
            </label>
            <h5 class="text-success pt-1" style="text-shadow: #a3cfbc 0 1px 2px;"">{{ restaurant.expense }}</h5>
            <p class="card-text">{{ restaurant.description }}</p>
            <p style="font-size:smaller;">
                
                {% if restaurant.full_service %}
                Full-Service<br>
                {% endif %}

                {% for cuisine in restaurant.cuisines %} 
                {{ cuisine }}<br>
                {% endfor %}

              </p>
            <button class="btn btn-primary btn-sm py-1 mb-2 shadow" type="button" data-bs-toggle="collapse" data-bs-target="#collapseReviews" aria-expanded="false" aria-controls="collapseReviews">
                See Reviews <i class="fa-solid fa-arrow-right"></i>
            </button>
            {% if current_user.is_authenticated %}
            {% if rated %}
            <div class="py-3">
                <h5>You have already reviewed this place, thanks!</h5>
            </div>
            {% else %}
            <div class="container justify-content-md-center" style="padding-top: 5%;">
                <form class="" method="post" action="{{ url_for('restaurants_bp.eating_place', rest_id=restaurant.rest_id) }}">
                    <h2 class="heading">Leave a Review</h2>
                        {{ form.csrf_token }}
                    <div class="form-group m-2">
                        {{ form.star_rating.label }}
                        {{ form.star_rating(class="form-select") }}
                    </div>
                    <div class="form-floating m-2">
                        {{ form.review(class="form-control", placeholder="comments", id="floatingTextarea2", style="height:200px;") }}
                        {{ form.review.label }}
                    </div>
                    <div class="form-group m-2">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>
                </form>
            </div>
            {% endif %}
            {% endif %}
            <div class="pt-2">
                <!-- <a class="btn btn-primary btn-sm" href="{{ url_for('restaurants_bp.restaurants') }}">Rate more restaurants</a><br> -->
            {% if restaurant.rest_id > 1 %}
                <a class="btn btn-outline-primary btn-sm shadow" href="{{ url_for('restaurants_bp.eating_place', rest_id=restaurant.rest_id-1) }}">Did you check out<br>{{ get_restaurant_by_id(restaurant.rest_id-1).name }}?</a>
            {% elif restaurant.rest_id == 1 %}
                <a class="btn btn-outline-primary btn-sm shadow" href="{{ url_for('restaurants_bp.eating_place', rest_id=rest_len) }}">Did you check out<br>{{ get_restaurant_by_id(rest_len).name }}?</a>

            {% endif %} 
            {% if restaurant.rest_id < rest_len %}
                <a class="btn btn-outline-primary btn-sm shadow" href="{{ url_for('restaurants_bp.eating_place', rest_id=restaurant.rest_id+1) }}">Want to check out<br>{{ get_restaurant_by_id(restaurant.rest_id+1).name }}?</a>
            </div> 
            {% elif restaurant.rest_id == rest_len %}
                <a class="btn btn-outline-primary btn-sm shadow" href="{{ url_for('restaurants_bp.eating_place', rest_id=1) }}">Want to check out<br>{{ get_restaurant_by_id(1).name }}?</a>
        </div> 

            {% endif %}
    </div>
</div>
    <div class="collapse col-lg-5" id="collapseReviews">
        <div class="card card-body" style="overflow:auto; height:90%; width:90%;">
            <h2 style="font-family:Noto; font-style:italic;">Reviews</h2>
            {% for each in restaurant_reviews(restaurant.rest_id) %}
            <ul>
                <dl class="row" style="font-style:italic; font-weight: bold;">{{ (get_user_by_id(each.user_id).username).title() }}:</dl>
                <dt class="text-warning fw-normal col" style="text-shadow: #172c65 0 1px 1px;"><i class="fa-solid fa-star"></i> {{ get_star_rating(user_id=each.user_id, rest_id=restaurant.rest_id) }}</dt>
                {% if each.review == '' %}
                <dd class="col text-muted" style="font-style: italic;">No written review</dd>
                {% else %} 
                <dd class="col">"{{ each.review }}"</dd>
                {% endif %}
                {% if current_user.is_authenticated %}
                {% if get_user_by_id(each.user_id).username == current_user.username %}
                <a class="btn btn-sm btn-outline-warning shadow" href="{{ url_for('users_bp.my_contributions') }}">Edit review</a>
                {% endif %}
                {% endif %}
            </ul>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

eating/templates/footer.html
<footer class="navbar navbar-expand-lg justify-content-around text-white mt-5" style="background-color: #3081C3;">
    <div class="container-fluid justify-content-space-between">
        
        <a class="navbar-brand ms-2" style="font-family:Noto; font-style:italic;" href="#">
            <img src="{{ url_for('static', filename='images/rorster.ico') }}" style="max-height: 80px;" class="d-inline-block align-text-bottom">RJF
        </a>
        <div class="navbar-item">
            © 2022 Copyright: Rory Industries
        </div>
        <a class="link-light me-3" href="https://portfolio-sean-fagan.herokuapp.com/" target="_blank"><i class="fa-solid fa-magnifying-glass-arrow-right"></i>Sean's Portfolio!</a>
    </div>
    
</footer>

eating/templates/fountain_place.html
{% extends 'base.html' %}

{% include 'navbar.html' %}

{% block title %}A Drinking Fountain{% endblock %}

{% block content %} 


{% if current_user.is_authenticated %}
{% if rated %}
    <div>
        <h5>You have already reviewed this place, thanks!</h5>
        <a class="btn btn-outline-warning btn-sm mb-2 shadow" href="{{ url_for('users_bp.my_contributions') }}">Edit your review</a>
    </div>
{% else %}
    <div class="container justify-content-md-center" style="padding-top: 5%;">
        <form class="" method="post" action="{{ url_for('fountains_bp.fountain_place', fountain_id=fountain.id) }}">
            Fountain {{ fountain.name }}
            <h2 class="heading">Leave a Review</h2>
                {{ form.csrf_token }}
            <div class="form-group m-2">
                {{ form.star_rating.label }}
                {{ form.star_rating(class="form-select") }}
            </div>
            <div class="form-floating m-2">
                {{ form.review(class="form-control", placeholder="comments", id="floatingTextarea2", style="height:200px;") }}
                {{ form.review.label }}
            </div>
            <div class="form-group m-2">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
{% endif %}
{% endif %}

{% endblock %}

eating/templates/hp_image_preview.html
<img src="../static/images/hp_image_preview.png"/>

<!-- <body style="background-image: url('../static/images/hp_image_preview.png'); width: 100%;"></body> -->

eating/templates/my_contributions.html
{% extends 'base.html' %}

{% block title %}My Contributions{% endblock %}

<body>
    {% include 'navbar.html' %}
    {% block content %}

    <div class="d-flex row">
        <div style="margin: 2% 0; text-align: center;">
            <h2>Greetings, {{ (current_user.username).title() }}!</h2>
            <h5>Thanks for your contributions so far! You can edit any of your reviews below.</h5>
        </div>

        <div class="container justify-content-md-center m-4">
            {% for review in reviews %}
            <div class="container p-4">
                <a class="link-primary" href="{{ url_for('restaurants_bp.eating_place', rest_id=review.rest_id) }}" style="text-decoration:none; text-shadow: rgba(0, 0, 0, 0.493) 2px 5px 11px;"> <dl class="row h5" style="font-style:italic; font-weight: bold;">{{ get_restaurant_by_id(review.rest_id).name }}</dl></a>
                <dt class="text-warning col"><i class="fa-solid fa-star"></i> {{ review.star_rating }}</dt>
                <dd class="col">"{{ review.review }}"</dd>
                <!-- Modal trigger Buttons -->
                <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#modal{{ review.rating_id }}">
                    Edit
                </button>
                <button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ review.rating_id }}">
                    Delete Review
                </button>
                <!-- Modal -->
                <div class="modal fade" id="modal{{ review.rating_id }}" tabindex="-1" aria-labelledby="modal{{ review.rating_id }}Label" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modal{{ review.rating_id }}Label">Edit Review for {{ get_restaurant_by_id(review.rest_id).name }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form class="" method="post" action="{{ url_for('users_bp.my_contributions') }}">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                    <input type="hidden" name="rest_id" value="{{ review.rest_id }}">
                                    <div class="form-floating py-2">
                                        <select class="form-select" id="floatingSelectGrid" name="star_rating">
                                            <option hidden value="{{ review.star_rating }}">You rated: {{ review.star_rating }} ⭐️</option>
                                            <option value="1">⭐️</option>
                                            <option value="2">⭐️⭐️</option>
                                            <option value="3">⭐️⭐️⭐️</option>
                                            <option value="4">⭐️⭐️⭐️⭐️</option>
                                            <option value="5">⭐️⭐️⭐️⭐️⭐️</option>
                                        </select>
                                        <label class="">Update Rating:<p class="text-warning" style="display:inline; font-size:smaller;"></p></label>
                                    </div>
                                    <div class="form-floating">
                                        <textarea type="text-field", name="review" class="form-control", id="floatingInputGrid", style="height:200px;")>{{ review.review }}</textarea>
                                        <label for="floatingInputGrid">Update review:</label>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <input type="submit" name="submit" value="Save Changes" class="btn btn-primary"></input>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Modal -->
                <div class="modal fade" id="deleteModal{{ review.rating_id }}" tabindex="-1" aria-labelledby="deleteModal{{ review.rating_id }}Label" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="deleteModal{{ review.rating_id }}Label">Are you sure you want to delete this rating?</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body" style="font-style:italic;">
                          You can always rate this restaurant again later.
                        </div>
                        <div class="modal-footer">
                          <form class="" method="post" action="{{ url_for('users_bp.my_contributions') }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="hidden" name="rating_" value="{{ review.rating_id }}">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <input type="submit" name="submit_delete" value="Yes, Delete" class="btn btn-danger"></input>
                          </form>
                        </div>
                      </div>
                    </div>
                </div>
                <!-- End 2nd Modal -->
            </div>

            {% endfor %}
        </div>

    {% endblock %}

eating/templates/navbar.html
<nav
  class="navbar bg-primary navbar-dark navbar-expand-lg"
  style="font-family: Noto, sans-serif"
>
  <div class="container-fluid justify-content-space-between">
    <div class="col col-lg">
      <a
        class="navbar-brand"
        style="
          font-family: Noto;
          font-style: italic;
          font-size: 2.5rem;
          text-shadow: #664d03 1px 1px 2px;
        "
        href="{{ url_for('main.home') }}"
        >Eating Disneyland</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="true"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div
      class="collapse navbar-collapse justify-content-end"
      id="navbarNav"
      style="text-shadow: #664d03 1px 1px 1px"
    >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{{ url_for('main.home') }}"
            >Home</a
          >
        </li>
        <li class="nav-item px-4">
          <a class="nav-link" href="{{ url_for('restaurants_bp.restaurants') }}"
            >Eating Places</a
          >
        </li>
        {% if current_user.is_authenticated %} {% if current_user.username
        =='tinytim' %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('restaurants_bp.add_restaurant') }}"
            >Add Restaurant</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('fountains_bp.add_fountain') }}"
            >Add Fountain</a
          >
        </li>
        {% endif %}
        <li class="navbar-text">
          Logged in as:
          <!-- <a class="nav-link-disabled" style="color: beige;">{{ current_user.username }}</a> -->
        </li>
        <li class="nav-item-dropdown dropdown">
          <a
            class="nav-link dropdown-toggle"
            style="font-style: italic"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{ current_user.username }}
            <img
              src="{{ url_for('static', filename='/images/D.png') }}"
              alt=""
              width="24"
              height="18"
              class="d-inline-block align-text-top"
            />
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            style="text-shadow: none"
            aria-labelledby="navbarDropdown"
          >
            <li>
              <a class="dropdown-item" href="{{ url_for('users_bp.profile') }}"
                >Update Profile</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{{ url_for('users_bp.my_contributions') }}"
                >My Contributions</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{{ url_for('auth_bp.logout') }}">Logout</a>
            </li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item-dropdown dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Login/Register
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            style="text-shadow: none"
            aria-labelledby="navbarDropdown"
          >
            <li>
              <a class="dropdown-item" href="{{ url_for('auth_bp.login') }}">Login</a>
            </li>
            <li>
              <a class="dropdown-item" href="{{ url_for('auth_bp.register') }}"
                >Register</a
              >
            </li>
          </ul>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% with messages = get_flashed_messages(with_categories=true) %} {% if messages
%} {% for category, message in messages %}
<div class="alert alert-{{ category }}" role="alert" id="flashMessage">
  <p>{{ message }}</p>
</div>
{% endfor %} {% endif %} {% endwith %}

eating/templates/register.html
{% extends 'base.html' %}

{% include 'navbar.html' %}

{% block title %}Sign on up!{% endblock %}

{% block content %} 
<div class="container justify-content-md-center pt-5" style="height:73%;">
<form class="" method="post" action="{{ url_for('users_bp.register') }}">
    <h2 class="heading">Register an account</h2>
        {{ form.csrf_token }}
    <div class="form-group m-2 col-4">
        {{ form.username.label }}
        {{ form.username(class="form-control") }}
    </div>
    <div class="form-group m-2 col-4">
        {{ form.password.label }}
        {{ form.password(class="form-control") }}
    </div>
    <div class="form-group m-2 col-4">
        {{ form.email.label }}
        {{ form.email(class="form-control") }}
    </div>
    <div class="form-group m-2 col-4">
        {{ form.zipcode.label }}
        {{ form.zipcode(class="form-control") }}
    </div>
    <div class="form-group m-2 col-2">
        {{ form.age.label }}
        {{ form.age(class="form-control") }}
    </div>
    <div class="form-group m-2 col">
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
</div>



{% endblock %}